# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartoBase
                                 A QGIS plugin
 Crea un proyecto con la cartografía base seleccionada
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-31
        copyright            : (C) 2023 by Francisco Gómez Losada
        email                : pgomezlosada@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CartoBase class from file CartoBase.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .carto_base import CartoBase
    return CartoBase(iface)
