# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartoBaseDockWidget
                                 A QGIS plugin
 Crea un proyecto con la cartografía base seleccionada
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-31
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Francisco Gómez Losada
        email                : pgomezlosada@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtWidgets import *

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'carto_base_dockwidget_base.ui'))


class CartoBaseDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(CartoBaseDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        print('empezamos')
        print(self.comboBox.currentText())
        print(self.treeWidget)

        # tree = your_qtreewidget  # replace every 'tree' with your QTreeWidget
        strings = ['jhfj<hfj','aaaaa','kjkfs']
        l = []  # list of QTreeWidgetItem to add
        for i in strings:
            l.append(QTreeWidgetItem([i]))  # create QTreeWidgetItem's and append them
        self.treeWidget.addTopLevelItems(l)  # add everything to the tree
        # # add the items to the QTreeWidget
        # self.treeWidget.insertTopLevelItems(1, l)





    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()