# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CartoBaseDockWidget
                                 A QGIS plugin
 Crea un proyecto con la cartografía base seleccionada
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-31
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Francisco Gómez Losada
        email                : pgomezlosada@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.core import *

from PyQt5.QtGui import QIcon
from PyQt5.QtCore import Qt

from PyQt5.QtWidgets import *
from qgis.PyQt.QtWidgets import QMessageBox

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

import shutil

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'carto_base_dockwidget_base.ui'))
pathplugin = os.path.dirname(__file__)


class CartoBaseDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(CartoBaseDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # Disparadores
        self.selectFolder.clicked.connect(lambda: self.SELECT_FOLDER_AND_PROJECT(self.pathFolder))
        self.selectFolderProject.clicked.connect(lambda: self.SELECT_FOLDER(self.pathFolderProject))
        self.createProject.clicked.connect(lambda: self.CREATE_PROJECT())
        self.treeWidget.itemActivated.connect(self.selectTreeChilds) #Función selección hijos en el árbol (con el doble click)
        self.treeWidget.clear()
        # self.idItem = 0
        # self.dictItems = {}



    def SELECT_FOLDER(self,qt_element):
        folder = QFileDialog.getExistingDirectory(None, "Selecciona Carpeta", "", QFileDialog.DontResolveSymlinks)
        qt_element.setText(folder)
 


    def SELECT_FOLDER_AND_PROJECT(self,qt_element):
        folder = QFileDialog.getExistingDirectory(None, "Selecciona Carpeta", "", QFileDialog.DontResolveSymlinks)
        qt_element.setText(folder)
        self.treeWidget.clear()
        if os.path.isdir(folder):
            self.load_project_structure(folder,self.treeWidget) # pathFolder seleccionar la ruta



    def CREATE_DIR(self, folder):
        """
        Create directory
        """
        if not os.path.isdir(folder):
            try:
                os.mkdir(folder)
            except:
                QMessageBox.warning(self,"Error","No se pudo crear la carpeta en la ruta: "+folder+". Intente crear la ruta manualmente.")
    


    def selectTreeChilds(self, item, column, select = 0):
        # Recorrer todos los elementos secundarios y seleccionarlos
        if select == 0:
            if item.isSelected():
                select == 1 #False
                selectBool = True
            else:
                select == 2
                selectBool = False
        else:
            if select == 1:
                selectBool = True
            else:
                selectBool = False
        for i in range(item.childCount()):
            child_item = item.child(i)
            child_item.setSelected(selectBool)
            self.selectTreeChilds(child_item, column, select=selectBool) #AttributeError: 'QTreeWidget' object has no attribute 'selectTreeChilds'
    


    def load_project_structure(self, startpath, tree):
        """
        Load Project structure tree
        :param startpath: 
        :param tree: 
        :return: 
        """
        lista_vectoriales = ('.shp','.gpk')
        lista_raster = ('.tif','.ecw')
        lista_todos = ('.shp','.gpk','.tif','.ecw')
        for element in os.listdir(startpath):
            path_info = startpath + "/" + element
            si_formato = 0
            for ext in lista_todos:
                if element.endswith(ext):
                    si_formato = 1
            if si_formato == 1 or os.path.isdir(path_info):
                parent_itm = QTreeWidgetItem(tree, [os.path.basename(element)])
                parent_itm.setData(0, Qt.UserRole, path_info) #Se le guarda la ruta al objeto internamente (se ve en el panel el nombre, pero no la ruta)
            if os.path.isdir(path_info): #Se comprueba si es un directorio
                self.load_project_structure(path_info, parent_itm)
                parent_itm.setIcon(0, QIcon(os.path.join(pathplugin,'icon','folder.png')))
            else: #Si no es un directorio...
                definido = 0
                for ext in lista_vectoriales:
                    if element.endswith(ext): #Comprobar si es extensión vectorial y añade icono
                        parent_itm.setIcon(0, QIcon(os.path.join(pathplugin,'icon','file_vectorial.png')))
                        definido = 1
                        break
                if definido == 0: #Si es 0 no es vectorial y ñade icono raster
                    for ext in lista_raster:
                        if element.endswith(ext):
                            parent_itm.setIcon(0, QIcon(os.path.join(pathplugin,'icon','file_raster.png')))
                            definido = 1
                            break
    


    def CREATE_PROJECT(self):
        # Comprobar nombre proyecto
        if self.nameProject.text() != '':
            nameProject =  self.nameProject.text()
            pass 
        else: 
            return QMessageBox.warning(self,"Error","No se ha introducido un nombre para el proyecto")
        
        # Comprobar directorio
        if os.path.isdir(self.pathFolderProject.text()):
            pathFolderProject = self.pathFolderProject.text()
            pass 
        else: 
            return QMessageBox.warning(self,"Error","Carpeta de proyecto no válida")

        # Comprobar directorio
        if os.path.isdir(self.pathFolder.text()):
            pathFolder = self.pathFolder.text()
            pass 
        else: 
            return QMessageBox.warning(self,"Error","Acceso a capas no válido")
        
        # Comprobar que elementos del árbol estan seleccionados
        selected_items = self.treeWidget.selectedItems()
        paths_source = [] #Esta será la lista donde se añaden las rutas de los elementos seleccionados
        for item in selected_items: #Comprueba los items seleccionados y añade la ruta a paths_source
            # Haz algo con el elemento seleccionado
            paths_source.append(item.data(0, Qt.UserRole)) #Recupera la ruta guardada internamente con Data de la línea 135

        paths_target = [f.replace(pathFolder,pathFolderProject) for f in paths_source] #Reemplaza las rutas de origen de las capas por las nuevas rutas de destino (carpeta proyecto elegida)

        
        # Comprobar CRS seleccionado
        selected_CRS = self.selectProjection.crs().postgisSrid()
        
        project = self.createProjectQGIS(pathFolderProject, nameProject, selected_CRS)

        for path_source, path_target in zip(paths_source, paths_target):# bucle con dos variables a la vez
            if os.path.isdir(path_source): #Comprobar si es un directorio
                os.makedirs(path_target, exist_ok=True) #Crear directorio si lo es y de forma recursiva (creando las carpetas y subcarpetas donde este el archivo)
            else:
                os.makedirs(os.path.dirname(path_target), exist_ok=True)
                shutil.copyfile(path_source, path_target) #Copia la ruta del origen a la capa de destino
                filename = os.path.basename(path_target)
                name_layer = os.path.splitext(filename)[0]
                ext_layer = os.path.splitext(filename)[1]
                if ext_layer in ('.shp'):
                    type_layer = 'shp'
                else:
                    type_layer = 'raster'

                self.addLayerToProject(project, path_target, type_layer = type_layer, name_layer = name_layer) #path_target.replace(pathFolderProject,'')
                #Integrar copy shp y otros
        
        self.saveProject(project)
        #Aquí mensaje de que ha creado el proyecto
        # Tenemos que copiar todos los archivos con extensiones auxiliares a shp
        #Tenemos que reemplazar sobre source_shp la extension del shp por las otras extensiones. Y cada vez, comprobar si el archivo existe (os.path.isfile)
        # Si existe, debemos copiar el archivo a la nueva ruta target_shp, teniendo en cuenta que debemos reemplazar nuevamente la extension del archivo de destino
        
    

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()



    def copySHP(source_shp,target_shp):
        EXTENSIONES_SHP = ['.cpg','.dbf','.prj','.sbn','.sbx','.shp.xml','shx']
        for ext in EXTENSIONES_SHP:
            print(ext)
            #Reemplazar terminación shp por ext y utilizar copy desde source a target source es un archivo
            #Shutil.CopyFile chequeando si el archivo existe



    def createProjectQGIS(self, path, filename, crs):
        """
        Create project QGIS with path and filename
        """
        path_file = os.path.join(path, filename+'.qgs')
        project = QgsProject()
        project.setFileName(filename)
        project.setCrs(QgsCoordinateReferenceSystem(crs, QgsCoordinateReferenceSystem.EpsgCrsId))
        self.saveProject(project, path_file)
        return project



    def saveProject(self, project, path_save=None):
        """
        Save project:  path_save automatic when None from current path
        """
        if path_save==None:
            project.write(project.absoluteFilePath())
        else:
            project.write(path_save)
        return project


    def addLayerToProject(self, project, path_layer, type_layer = 'shp', name_layer=''):
        """
        Add vector/raster layers to project 
        """

        if type_layer == 'shp':
            provider = 'ogr'
            layer = QgsVectorLayer(path_layer,name_layer,provider)
            layer.setProviderEncoding(u'UTF-8')
        elif type_layer == 'raster':
            layer = QgsRasterLayer(path_layer,name_layer)
        else:
            return QMessageBox.warning(self,"Error",f"Error en la capa: {name_layer}. No se reconoce el tipo")
        
        #Add qml
        
        # if qml_path != None:
        #     layer.loadNamedStyle(qml_path)
            
        project.addMapLayer(layer,False) #Se añade al mapa pero no aparece en el árbol
        root = project.layerTreeRoot()
        root.insertChildNode(0, QgsLayerTreeLayer(layer)) #Se añade al árbol de capas. el índice 0 indica la posición en el árbol de capas
        root.findLayer(layer.id()).setExpanded(False) #La capa aparece sin expandir
        root.findLayer(layer.id()).setItemVisibilityChecked(False) #La capa aparece no visible

